<?php
$GLOBALS['_access_level']=array('auth'=>65534,'all'=>65535,'login'=>1,'profile_view'=>7,'search_photo'=>7,'message_read'=>6,'message_write'=>6,'flirt_read'=>6,'flirt_send'=>6,'upload_photos'=>6,'write_comments'=>7,'read_blogs'=>7,'write_blogs'=>6,'view_album'=>7,'view_photo'=>7,'manage_folders'=>6,'saved_messages'=>6,'search_basic'=>7,'search_advanced'=>7,'manage_networks'=>6,'save_searches'=>6,'inbox'=>6,'search_blog'=>7,'contact'=>7);
$GLOBALS['_allow_na']=array (
  'auth' => 1,
  'all' => 1,
  'login' => 1,
  'profile_view' => 1,
  'search_photo' => 1,
  'message_read' => 1,
  'message_write' => 0,
  'flirt_read' => 1,
  'flirt_send' => 0,
  'upload_photos' => 1,
  'write_comments' => 0,
  'read_blogs' => 1,
  'write_blogs' => 1,
  'view_album' => 1,
  'view_photo' => 1,
  'manage_folders' => 1,
  'saved_messages' => 1,
  'search_basic' => 1,
  'search_advanced' => 1,
  'manage_networks' => 1,
  'save_searches' => 1,
  'inbox' => 1,
  'search_blog' => 1,
  'contact' => 1,
);
